--- # This is my  first YAML playbook for Ansible
- hosts: webservers
  user: ansadmin
  become: yes					(Header)
  connection: ssh
  gather_facts: yes
  
  tasks:
   - name: Install Git
     become_method: su
     yum: name=git state=installed

   - name: Install Httpd
     become_method: su
     yum: name=httpd state=installed
